version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    labels:
      traefik.enable': 'true'
      traefik.http.middlewares.${COMPOSE_PROJECT_NAME]-https-redirect.redirectscheme.scheme': 'https'
      traefik.http.routers.${COMPOSE_PROJECT_NAME]-secure.entrypoints': 'https'
      traefik.http.routers.${COMPOSE_PROJECT_NAME]-secure.rule': 'Host(`${DNS_HOSTNAME}`)'
      traefik.http.routers.${COMPOSE_PROJECT_NAME]-secure.service': '${COMPOSE_PROJECT_NAME]'
      traefik.http.routers.${COMPOSE_PROJECT_NAME]-secure.tls': 'true'
      traefik.http.routers.${COMPOSE_PROJECT_NAME]-secure.tls.certresolver': 'http'
      traefik.http.routers.${COMPOSE_PROJECT_NAME].entrypoints': 'http'
      traefik.http.routers.${COMPOSE_PROJECT_NAME].middlewares': '${COMPOSE_PROJECT_NAME]-https-redirect'
      traefik.http.routers.${COMPOSE_PROJECT_NAME].rule': 'Host(`${DNS_HOSTNAME}`)'
      traefik.http.services.${COMPOSE_PROJECT_NAME].loadbalancer.server.port': '80'
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
