version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.${DNS_HOSTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${DNS_HOSTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${DNS_HOSTNAME}-secure.rule=Host(`${DNS_HOSTNAME}`)"
      - "traefik.http.routers.${DNS_HOSTNAME}-secure.service=${DNS_HOSTNAME}"
      - "traefik.http.routers.${DNS_HOSTNAME}-secure.tls=true"
      - "traefik.http.routers.${DNS_HOSTNAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${DNS_HOSTNAME}.entrypoints=http"
      - "traefik.http.routers.${DNS_HOSTNAME}.middlewares=${DNS_HOSTNAME}-https-redirect"
      - "traefik.http.routers.${DNS_HOSTNAME}.rule=Host(`${DNS_HOSTNAME}`)"
      - "traefik.http.services.${DNS_HOSTNAME}.loadbalancer.server.port=80"
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
