version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    networks:
      - default
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    networks:
      - default
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.${INT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${INT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${INT_NAME}-secure.rule=Host(`${DNS_HOSTNAME}`)"
      - "traefik.http.routers.${INT_NAME}-secure.service=${INT_NAME}"
      - "traefik.http.routers.${INT_NAME}-secure.tls=true"
      - "traefik.http.routers.${INT_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${INT_NAME}.entrypoints=http"
      - "traefik.http.routers.${INT_NAME}.middlewares=${INT_NAME}-https-redirect"
      - "traefik.http.routers.${INT_NAME}.rule=Host(`${DNS_HOSTNAME}`)"
      - "traefik.http.services.${INT_NAME}.loadbalancer.server.port=80"
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
networks:
  default:
    external:
      name: vrack

